### ISSUE TITLE
Error in client config

### ISSUE THREAD

**Issue by alokat** [andres-erbsen/dename#27]
Looks like there is something wrong with your base64 public key in the client config:
$ dnmlookup andres pgp  
panic: /home/you/.config/dename/authorities.cfg:7:22: string not terminated

goroutine 1 [running]:
main.main()
        /home/you/go/src/github.com/andres-erbsen/dename/dnmlookup/main.go:59 +0x6c2

goroutine 2 [runnable]:
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:90
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
        /usr/local/go/src/runtime/mgc0.go:82
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
        /usr/local/go/src/runtime/malloc.go:712
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

**Comment by alokat** [comment]
Fixed problem, was just a typo error.
https://github.com/alokat/dename/commit/de01506277c703a304645780e3f940c3600512f8

**Comment by alokat** [comment]
Can be closed.
